# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  
  pod 'MJCorePod',    :path => 'MJCorePod'  # YYKit

  #极光
  pod 'JVerification', '~> 3.2.1'
  pod 'JPush', '~> 4.6.4'

# 合力亿捷客服
  pod 'HCHollyOC', '~> 0.9.6'

#Bugly

  pod 'Bugly', '~> 2.6.1'

#友盟
  pod 'UMCCommon', '7.1.3'

#腾讯IM相关，另手动添加了UI库TUIKit
  pod 'TXIMSDK_Plus_iOS_Bitcode', '5.8.1672'
  pod 'TXLiteAVSDK_Professional', '~> 11.4.14445'

# 极验
  pod 'GT3Captcha-iOS', '0.15.2'

#巨量引擎
  pod 'BDASignalSDK', '1.0.3'

  #UI
    pod 'Masonry', '1.1.0'
    pod 'MMLayout', '0.2.0'
    pod 'MJRefresh', '3.7.9'
    pod 'DZNEmptyDataSet', '1.8.1'
    pod 'TPKeyboardAvoiding', '1.3.5'
    pod 'JXCategoryView', '1.5.2'

   
#网络请求库
    pod 'AFNetworking', '~> 4.0.1'
    pod 'JSONModel', '~> 1.8.0'
    pod 'Reachability', '3.7.6'
    pod 'SDWebImage', '5.19.1'

# 提示
    pod 'JDStatusBarNotification', '~> 1.6.1'
    pod 'MBProgressHUD', '~> 1.2.0'

#动画库
    pod 'FLAnimatedImage', '1.0.12'
    pod 'JHChainableAnimations', '3.0.1'
    pod 'SVGAPlayer', '2.3.4'
    pod 'QGVAPlayer', '~> 1.0.16'
    pod 'pop', '1.0.12'

#数据存储
    pod 'WCDB', '~> 1.0.7.5'
    pod 'WCDBOptimizedSQLCipher', '1.2.1'# WCDB依赖的

    pod 'ReactiveObjC', '3.1.0'
    pod 'SocketRocket', '0.5.1'
    pod 'SSZipArchive', '2.2.2'
    pod 'AvoidCrash', '2.5.2'
    
    pod 'StreamingKit', '~> 0.1.30'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end

    flutter_additional_ios_build_settings(target)
  end
  
  # Bitcode 处理
       bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
       def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
         framework_path = File.join(Dir.pwd, framework_relative_path)
         command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
         puts "Stripping bitcode: #{command}"
         system(command)
       end
       framework_paths = [
         "/Pods/TXIMSDK_Plus_iOS_Bitcode/ImSDK_Plus.framework/ImSDK_Plus",
       ]
       framework_paths.each do |framework_relative_path|
         strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
       end

end
