name: Build and Distribute (Fixed)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.35.1'
          
      # 检查可用的 Xcode 版本
      - name: List Available Xcode Versions
        run: ls -la /Applications/ | grep "Xcode"

      # 使用 Xcode 15.4 (更稳定)
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app
        
      # 安装 iOS 平台
      - name: Install iOS Platform
        run: |
          echo "安装 iOS 平台..."
          sudo xcodebuild -downloadPlatform iOS
          sudo xcodebuild -downloadPlatform iOS Simulator
          
          echo "检查可用的 iOS 平台..."
          xcrun simctl list runtimes
          
      - name: Setup Flutter Environment
        run: |
          flutter clean
          flutter pub get
          flutter pub upgrade
          flutter doctor -v
          
      # 设置 iOS 部署目标为 13.0
      - name: Set iOS Deployment Target
        run: |
          echo "设置 iOS 部署目标为 13.0..."
          cd ios
          plutil -replace IPHONEOS_DEPLOYMENT_TARGET -string "13.0" Runner.xcodeproj/project.pbxproj
          plutil -replace MinimumOSVersion -string "13.0" Flutter/AppFrameworkInfo.plist
          cd ..
          
      # 清除 Xcode 缓存
      - name: Clean Xcode Cache
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/Library/Developer/Xcode/iOS\ DeviceSupport
          rm -rf ~/Library/Developer/Xcode/Archives
          rm -rf ~/Library/Developer/Xcode/Products
          
      # 检查构建环境
      - name: Check Build Environment
        run: |
          echo "检查 iOS SDK..."
          xcodebuild -showsdks | grep iOS
          
          echo "检查构建配置..."
          cd ios
          xcodebuild -list -project Runner.xcodeproj
          cd ..
          
      # 手动构建 iOS 应用
      - name: Build iOS App
        run: |
          echo "开始构建 iOS 应用..."
          
          # 设置证书和配置文件
          echo "MIIMiQIBAzCCDFAGCSqGSIb3DQEHAaCCDEEEggw9MIIMOTCCBtcGCSqGSIb3DQEHBqCCBsgwggbEAgEAMIIGvQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQI1/qI15isFfwCAggAgIIGkGoNetdU/mWJGB3w6a/2exnygLYQnTeQp4s4OBDCviRlEGX2qrtf3MKcTffo2EvJ0obUhFhJm5ItbV7RSLk30lUxNWtFlROTYflwmXDCdtLmAIAHUbPyn4ACyaVaushx7YlkHmZ953rQEG6A6aHGGGrlYdz0M/pWfAd+uhsYDl6YfJT2wGJAxV3Dh6931gKwMriMGq36lbBh17ofFGALhI4A7fmXqc5e6Q5rxjDP/fEZENX4+wh05SkPW1vK0oc6XaAqqKTL+EXZWfw62IF6Fax0Rjp7LLsy5JcbxPBtWO9wU7ghfkFePOXLEqXSp+MwWNFruzyikNKs95oAcsIMX+uQC69+Ywc+Gx85mUo+MNU2lmMx6GiOwLVmB8ZNexEcxJmCX1hZgLeyBC1Nxm46LINAqTW9KLHT7ZQUDRSoQZdENWIh9VT2JhAD6g0jRwG25X6EjLSvQuqHeXMpmxzayN9cvRl2mPrGkZHzhcpRfnjfaWZy39lh1Eq47MnOlrcz/dLTrYBJkQ5REo/I3Y/eKr1HeSG9LTArIgCE6wHbls22PSMc/gxDoudXMhNjWf4d5SMwGagHJd2P0kz5etFF9oa62sPApvosU4tWVlBS+LFlFtMV8xdsPFAsZwKfB2zh9Glf97uGAV5KE5TetmGFmG4x9Kxj0rlCtqf1U4jdZjLr60EN5vApqhclzLqysVszNZytizWkxAOgrtljj92sTes4yRmGuixJZp1AJl6x6WNHft1GTmPHcsPGeCwfFqv1+NQBq9fpfai4IecRqy0v3tzC/VmVkfPPNQdOKGRS+MvbXrfzc55nIfZjiRmFNgAnHJEAszJwB2/9ThXfRFkTrh952P74LnP+Pa5HCUledJWv5AZ5wnzB7uFSqH6LnibrMQzk/Q1ivCj76oxO1pJivulRTsY+KWUD6w5gRIlKpcVBANp6OHdd7HujEE/3pHdXq3zWzWG1z2JSWB8ufWMMZSM2F4dJlQATmYAiRCxfnOjlo+JQQjjVAT3/fibrNMTX9O/lLOzNLC40znPFUWwj9O8kzECDGIwufSLWN5BPO4vSLq2rg0oAxNaQQhoFu+PS0eUz9GUqfdpqABaLP0XXLNNG9i9XX/FIzWeO7E+W9wcTQ8bLXcTAQrXmE55fjrr3MS9r4P5/p6URQn9kucPMpWOMgEvw2gsg8fml0RtsF4kQFZeiFoUAo0SUip5ZzoWUCem+/uGgtjSxUOCn6mZi0aUPQivTrdd4uPWPlx1Hxl6E/kxhuRC/SaxXnmpwqDgKJHsOMoGaaOdjLUa9pTVU72JaAVcmOb/xcFtfFXnblFH7bbhj8PGikcB8W4aXLg8RSmd1ACqQbITAn5EnPavRNebWqCSztlR8G2HVRd53pep3o+usyRYW3+KHC+tgAdwPYPvViGcTBgPcmHG9z3YPlqfxs7LbymbXC2/suz0CLBngh59GrlDFlGmZ4bBEaJ9e378RA9TA8az2Reu6hXsTKW0ympbOLLYqXX+Bz2P0nxK6grj/4iRtbI/lzBIXupu7tCEwyV9gYLfuK8sMxuyxbQRTiCDH24/ZjwZ5pCV8/uqVADSHnQdZbp5S5EsH3B8bx/nH66qpH8SI+kGCrveROhToxIbOgoVisPmfQ/ffH9nWe963ix4+xwpEuKVWC1lW2Awo0bjy3vm3QOhPHG2ZL7HAedpq+DRPmhTFAt1Qh2xaA94Dos96foWFmz/uteZDWcHr0ea4oyT+FJSC0T5oGZGKPX2uaTaLwQFVrRHy59MRoxdPpflkPjQqJOkCcfTPyp2rjfI3yL2QpPrXVVHrtw1S6HWZtAJ38UQjzicTbaiWSY+20vU7s9k0ereCKdSTfPQW3wAaDXoSnJM9Ng/w3cCtWf0jFP6oOAwHIIAaKpkICa8rVDZxwUbPXy3VF+tRnMQjmJOqiCUL+UQ96fy9kobSGHCKxIqfG9nrsd55wDjfKaUi4B0bowsaH30FHo5GCA7d9+dctCtvBNypHuleIEp4ohTIJVahklInlYEFicR/lyTMKPJPhcd1ldbUpOsb9vqe89EXJkOfmaXZ4RxPipFulR6W9HH/Pfw3Tk1CyYCFIwdA458O2BP6QvI9fRtTkE053d+nLOCLIfx/QzP+zna5MmkrlJ/A4CRdSXG4BKlJbGIW7QmoyDYfMJFqlkPPb77Im/TfvIpKWyc2rOwzT2qHKgM7qlYig7w1NNaw2g0cz/+FDqDwMmylSSD+k0ExyDCCBVoGCSqGSIb3DQEHAaCCBUsEggVHMIIFQzCCBT8GCyqGSIb3DQEMCgECoIIE7jCCBOowHAYKKoZIhvcNAQwBAzAOBAhxCzM9ToXrxgICCAAEggTISW0sJucAkMvmVUpH0Pw5+9yujAsnt/wYgImZTAh8wZ3KGVQCbu6Bb6IWo+++0dI6/P60jrgRxAAPH+W0WOiYvzM8sU0/kRI/kHe5QfVEUJopneognqNvulG1alYJdioKAMOpLUZvmGHVZ8w3vdM3yad3Tv6ZkGu+L8q5u0Hc1aYcafYg21p1ZTNpjatv6I5nB9jgx2O+M7XGFXjTGeYXLCDwUyHSweMEVklvGxg6WEHw6hoeDMq6ybV/u1MDZZEOGcAdNO7oTzJ+lkKpQH+pHy2gK8FWwO/6IrAGkhWah+GInFRktnWnCv1j41Iimz+aObD4cslOeidz9fZqVNIHuh91nULeDnKnj+rY52kpvt3mykSl6O7FeCjW9UxjbqrhoEYibBkLX6KHFaA0v0LyQnGaB2lv/aZgl9BLdfTrQuj9MHH81oAcCJRylcZr2QOUSGUHUh9SlEfyG9rOUlXaj4orqIrsZtTMTd0079AkMF8xl+eYTIqgkUDUJ7HMHcihQyFFNQQDZKBd2FeCFMBLdOvyrtrQFuxgi8X1gkmxroGDT/AqVutKrFDYLesXQ1/I/KWCafu+SBF+QGImEh5kY6e3EjIXhxmiXadyl2yMGJFZX+xafx+eXpjrwRhff6VzV7nsQuPfOe4rsPhnKcW3AShNJW4bp0Wl0hJcXX7YvLkJyRKdoGnpVd3rgzKIt7pecOzh8f/dzaksxrUVNxKSSBzzO9aLF6twd+1b1AlrKdyKgNQomRDiZfa+TUj9VihMwX+IInomqfOpmLDLC56QcNiO+u7D1PMXfvSqg1HEaxT4CUawJKHIrS9Kh4Rtheo8StKK2h7ctWm6DoSlqRoTDKmWvPmQMjoCsFKbsUZCs2lwz2PafToJuO9JMVqoXivEueJc4b+rBZwKlvJaQy5RhKQQ82kcnLaJ1KHhmf7ma1squIW/xXVKl+vw0W0L2ZqC2LiAe/i/hGcx+UPrZl9nQG9571fA5PMd/hGzxgNgeDaNLOu1q9QGDxmIdAsq+73kgjJGSy2HULfvrf0F81UvjCnGoQx8u5adu+/DnCP4Jv9xs/pjs4a4nb+Bj5y40tFaMXZ28TOJd4yR5LNsKRdb0SSKQxbmTdXizs/+7H4utVmZZcN1afA9Htz5cr7lmdxV2zP5MTF7gp9M5ISwFsZO1Ue/LkGz2dnbdK9tlpOUisc0kJW3srj1CPn8IcmDF7EqWncm6z9aYUy53udhyM7li/DNYBbZZkcKo4wF1+Lz4azsWiK9agQyEWFn1IkQSnXTKtp6sbyX8xJWguks2wj4MOPOOgV/AqwhrZSgrr1xvVun+6FFsfZUovP2st+jF717ZUZxzlwSkDU3KR0Q3E8Jnx6ViCV/FzrlTKGRMzIUYRz9/LCGjuKiQ/suN5OSu8wsIOwVx1gUZI96wSOd+YK1IatVSBFUEYDT3WP4SYTyqoHkcr7zoXanhDBQ/5xeihM6j8Smc8D1kSBFfnM9RLoG5M44/04ELYxw1MPBfDk+3wWD4gxzIMtpAYzSBsef92Gb9UVmYdSKI3YqxCf4k7vX95U9ZqmEthtmWGIcAEfgM66dur4rFEzz+jGswwGDrdyTpvBhtx2U0MgaZGluAX+TpYjVZEYkNqVoMT4wFwYJKoZIhvcNAQkUMQoeCABVAHMAZQByMCMGCSqGSIb3DQEJFTEWBBQbl6woPdGkbXJCRrrtwAilQRcMzTAwMCEwCQYFKw4DAhoFAAQUQyxjQwppUNmPXYORRyfouil8O1sECPfHqfN4HSB6AgEB" | base64 --decode > certificate.p12
          
          # 创建 keychain
          security create-keychain -p "111111" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "111111" build.keychain
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain
          
          # 导入证书
          security import certificate.p12 -k build.keychain -P "123456" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "111111" build.keychain
          
          # 构建应用
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist --no-tree-shake-icons --dart-define=FLUTTER_BUILD_NUMBER=${{ github.run_number }} --verbose

      - name: Archive IPA
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          path: build/ios/ipa
          
      - name: Upload to App Store using altool
        env:
          IPA_PATH: "build/ios/ipa/lookpartner.ipa"
          APPLE_ID: "linchunlei@sunsmarttech.shop"
          APP_SPECIFIC_PASSWORD: "qjku-rbrh-xqfp-ohsf"
        run: |
          xcrun altool --upload-app -f "$IPA_PATH" \
            -t ios \
            -u "$APPLE_ID" \
            -p "$APP_SPECIFIC_PASSWORD" \
            --verbose
